# Default values — override per environment
replicaCount: 2

image:
  repository: ghcr.io/shinobi0607/react-todo-devops
  tag: sha-2fec51b
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: todo.yourdomain.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
